[project]
name = "eswasa_verification"
authors = [
    { name = "ESWASA", email = "ict@eswasa.org.sz"}
]
description = "Public register + QR mark verification."
requires-python = ">=3.10"
readme = "README.md"
dynamic = ["version"]
dependencies = []

[build-system]
requires = ["flit_core >=3.4,<4"]
build-backend = "flit_core.buildapi"

[tool.bench.dev-dependencies]

[tool.ruff]
line-length = 110
target-version = "py310"
