/**
 * Typed empty-state scaffolds when Core returns no rows yet.
 * TODO: wire real — remove once Desk + Core always populate /governance/*.
 */
import type {
  BoardMember,
  GovernanceBody,
  GovernanceCalendarItem,
  GovernanceDeclaration,
  GovernanceMeeting,
  GovernanceRisk,
  PackSection,
  ResolutionAction,
} from "../api/types";

export const STUB_PACK_SECTIONS: PackSection[] = [
  {
    id: "p1",
    title: "Chair's agenda and previous minutes",
    source: "secretariat",
    owner: "T. Motsa",
    status: "ready",
    included: true,
    restricted: false,
  },
  {
    id: "p2",
    title: "CEO's report",
    source: "upload",
    owner: "B. Hlophe",
    status: "ready",
    included: true,
    restricted: false,
  },
  {
    id: "p3",
    title: "Certification performance",
    source: "live_module",
    owner: "Certification",
    status: "ready",
    included: true,
    restricted: false,
  },
  {
    id: "p4",
    title: "Standards development",
    source: "live_module",
    owner: "Standards",
    status: "ready",
    included: true,
    restricted: false,
  },
  {
    id: "p5",
    title: "Metrology and laboratory",
    source: "live_module",
    owner: "Metrology",
    status: "ready",
    included: true,
    restricted: false,
  },
  {
    id: "p6",
    title: "Management accounts, Aug 2026",
    source: "live_module",
    owner: "Finance",
    status: "overdue",
    included: true,
    restricted: false,
  },
  {
    id: "p7",
    title: "Risk register and heat map",
    source: "live_module",
    owner: "Risk & Compliance",
    status: "ready",
    included: true,
    restricted: false,
  },
  {
    id: "p8",
    title: "Resolution action tracker",
    source: "live_module",
    owner: "Secretariat",
    status: "ready",
    included: true,
    restricted: false,
  },
  {
    id: "p9",
    title: "Internal audit progress",
    source: "upload",
    owner: "Internal Audit",
    status: "awaiting",
    included: true,
    restricted: false,
  },
];

export const STUB_NEXT_MEETING: GovernanceMeeting = {
  id: "BM-2026-Q3",
  title: "Q3 Board meeting",
  body_name: "Full Board",
  scheduled_at: "2026-10-08T09:00:00",
  venue: "ESWASA Boardroom, Matsapha",
  hybrid: true,
  online_link: "Hybrid — Teams link issued with pack",
  pack_deadline: "2026-10-01",
  status: "Scheduled",
  attendance: [
    { member: "SD", rsvp: "yes", attended: null, apology: false },
    { member: "NS", rsvp: "yes", attended: null, apology: false },
    { member: "MM", rsvp: "yes", attended: null, apology: false },
    { member: "LN", rsvp: "yes", attended: null, apology: false },
    { member: "BH", rsvp: "yes", attended: null, apology: false },
    { member: "ZG", rsvp: "yes", attended: null, apology: false },
    { member: "TS", rsvp: "pending", attended: null, apology: false },
    { member: "PK", rsvp: "pending", attended: null, apology: false },
    { member: "SG", rsvp: "no", attended: null, apology: true },
  ],
};

export const STUB_ACTIONS: ResolutionAction[] = [
  {
    id: "ACT-001",
    description: "Publish 2027 fee schedule in the Government Gazette",
    resolution: "RES-2026-031",
    owner: "Legal Services",
    due_date: "2026-09-15",
    progress: 60,
    status: "Overdue",
    report_in_pack: true,
  },
  {
    id: "ACT-002",
    description: "Test DR failover for Frappe and Core",
    resolution: "RES-2026-030",
    owner: "ICT",
    due_date: "2026-09-20",
    progress: 40,
    status: "Overdue",
    report_in_pack: true,
  },
  {
    id: "ACT-003",
    description: "Draft traceability programme charter",
    resolution: "RES-2026-027",
    owner: "Metrology",
    due_date: "2026-09-25",
    progress: 80,
    status: "Overdue",
    report_in_pack: false,
  },
  {
    id: "ACT-004",
    description: "Notify industry of fee changes (CRM campaign)",
    resolution: "RES-2026-031",
    owner: "Marketing",
    due_date: "2026-10-05",
    progress: 20,
    status: "Open",
    report_in_pack: false,
  },
];

export const STUB_CALENDAR: GovernanceCalendarItem[] = [
  { id: "c1", title: "Board pack issue deadline", date: "2026-10-01", kind: "deadline" },
  { id: "c2", title: "Q3 Board meeting", date: "2026-10-08", kind: "meeting" },
  { id: "c3", title: "Audit & Risk Committee", date: "2026-10-15", kind: "meeting" },
  { id: "c4", title: "Annual report to Ministry of Commerce", date: "2026-10-31", kind: "statutory" },
  { id: "c5", title: "Term ends — Mr. Themba Shongwe", date: "2026-11-30", kind: "term" },
];

export const STUB_RISKS: GovernanceRisk[] = [
  {
    id: "RSK-004",
    title: "Loss of ISO/IEC 17025 accreditation at the metrology lab",
    category: "Operational",
    owner: "Head, Metrology",
    inherent_likelihood: 4,
    inherent_impact: 5,
    residual_likelihood: 3,
    residual_impact: 5,
    score: 15,
    band: "critical",
    trend: "worsening",
    status: "Open",
    flagged_for_pack: true,
  },
  {
    id: "RSK-011",
    title: "Revenue shortfall from delayed certification renewals",
    category: "Financial",
    owner: "CFO",
    inherent_likelihood: 4,
    inherent_impact: 4,
    residual_likelihood: 4,
    residual_impact: 4,
    score: 16,
    band: "critical",
    trend: "stable",
    status: "Open",
    flagged_for_pack: false,
  },
  {
    id: "RSK-002",
    title: "Cyber attack on public portals and e-store",
    category: "Technology",
    owner: "Head, ICT",
    inherent_likelihood: 4,
    inherent_impact: 5,
    residual_likelihood: 2,
    residual_impact: 5,
    score: 10,
    band: "high",
    trend: "improving",
    status: "Open",
    flagged_for_pack: false,
  },
  {
    id: "RSK-007",
    title: "Inability to retain technical auditors",
    category: "People",
    owner: "HR Manager",
    inherent_likelihood: 4,
    inherent_impact: 3,
    residual_likelihood: 3,
    residual_impact: 3,
    score: 9,
    band: "medium",
    trend: "worsening",
    status: "Open",
    flagged_for_pack: false,
  },
  {
    id: "RSK-013",
    title: "Non-compliance with PFM Act reporting deadlines",
    category: "Compliance",
    owner: "CFO",
    inherent_likelihood: 3,
    inherent_impact: 4,
    residual_likelihood: 2,
    residual_impact: 4,
    score: 8,
    band: "medium",
    trend: "stable",
    status: "Open",
    flagged_for_pack: false,
  },
  {
    id: "RSK-009",
    title: "Delay in adopting regional (SADC) harmonised standards",
    category: "Strategic",
    owner: "Head, Standards",
    inherent_likelihood: 3,
    inherent_impact: 3,
    residual_likelihood: 3,
    residual_impact: 2,
    score: 6,
    band: "medium",
    trend: "stable",
    status: "Open",
    flagged_for_pack: false,
  },
  {
    id: "RSK-015",
    title: "Reputational damage from a mis-certified product",
    category: "Reputational",
    owner: "Head, Certification",
    inherent_likelihood: 2,
    inherent_impact: 5,
    residual_likelihood: 1,
    residual_impact: 5,
    score: 5,
    band: "medium",
    trend: "improving",
    status: "Open",
    flagged_for_pack: false,
  },
  {
    id: "RSK-006",
    title: "Dependence on a single e-payment provider",
    category: "Operational",
    owner: "CFO",
    inherent_likelihood: 3,
    inherent_impact: 3,
    residual_likelihood: 2,
    residual_impact: 3,
    score: 6,
    band: "medium",
    trend: "stable",
    status: "Open",
    flagged_for_pack: false,
  },
];

export const STUB_MEMBERS: BoardMember[] = [
  {
    id: "m1",
    full_name: "Dr. Sibusiso Dlamini",
    role: "Chair",
    committees: ["Technical"],
    term_end: "2028-03-01",
    attendance_pct: 100,
    declaration_due: false,
  },
  {
    id: "m2",
    full_name: "Ms. Nokuthula Simelane",
    role: "Vice",
    committees: ["HR & Rem (Chair)"],
    term_end: "2028-03-01",
    attendance_pct: 100,
    declaration_due: false,
  },
  {
    id: "m3",
    full_name: "Adv. Lindiwe Nxumalo",
    role: "Member",
    committees: ["Audit & Risk (Chair)"],
    term_end: "2027-06-01",
    attendance_pct: 92,
    declaration_due: false,
  },
  {
    id: "m4",
    full_name: "Mr. Mandla Mamba",
    role: "Member",
    committees: ["Finance (Chair)", "Audit & Risk"],
    term_end: "2027-06-01",
    attendance_pct: 92,
    declaration_due: false,
  },
  {
    id: "m5",
    full_name: "Dr. Zanele Magagula",
    role: "Member",
    committees: ["Technical (Chair)"],
    term_end: "2029-01-01",
    attendance_pct: 85,
    declaration_due: false,
  },
  {
    id: "m6",
    full_name: "Mr. Themba Shongwe",
    role: "Member",
    committees: ["Finance", "HR & Rem"],
    term_end: "2026-11-01",
    attendance_pct: 77,
    declaration_due: true,
  },
  {
    id: "m7",
    full_name: "Mr. Peter Kunene",
    role: "Member",
    committees: ["Audit & Risk"],
    term_end: "2029-01-01",
    attendance_pct: 88,
    declaration_due: true,
  },
  {
    id: "m8",
    full_name: "Ms. Sakhile Gama",
    role: "Member",
    committees: ["Technical", "Finance"],
    term_end: "2027-06-01",
    attendance_pct: 85,
    declaration_due: false,
  },
  {
    id: "m9",
    full_name: "Mr. Bongani Hlophe",
    role: "Ex officio",
    committees: ["All committees, in attendance"],
    term_end: null,
    attendance_pct: 100,
    declaration_due: false,
  },
];

export const STUB_BODIES: GovernanceBody[] = [
  { id: "c1", name: "Audit & Risk", type: "Committee", chair: "Adv. Lindiwe Nxumalo", members: [], meeting_frequency: "Quarterly", quorum: 3 },
  { id: "c2", name: "Finance & Investment", type: "Committee", chair: "Mr. Mandla Mamba", members: [], meeting_frequency: "Quarterly", quorum: 3 },
  { id: "c3", name: "HR & Remuneration", type: "Committee", chair: "Ms. Nokuthula Simelane", members: [], meeting_frequency: "Bi-annually", quorum: 2 },
  { id: "c4", name: "Technical (Standards)", type: "Committee", chair: "Dr. Zanele Magagula", members: [], meeting_frequency: "Quarterly", quorum: 3 },
];

export const STUB_DECLARATIONS: GovernanceDeclaration[] = [
  {
    id: "d1",
    member: "m6",
    member_name: "Mr. Themba Shongwe",
    kind: "Annual",
    interest: "Due 8 Oct",
    filed_on: "2026-10-08",
  },
  {
    id: "d2",
    member: "m7",
    member_name: "Mr. Peter Kunene",
    kind: "Annual",
    interest: "Due 8 Oct",
    filed_on: "2026-10-08",
  },
  {
    id: "d3",
    member: "m4",
    member_name: "Mr. Mandla Mamba",
    kind: "Meeting",
    interest: "Item 6 — recuse",
    action: "Recuse",
    filed_on: "2026-02-01",
  },
];

export function sourceLabel(source?: string | null): string {
  switch (source) {
    case "live_module":
      return "Live module";
    case "upload":
      return "Paper upload";
    case "secretariat":
      return "Secretariat";
    default:
      return source || "—";
  }
}

/** Alias for Overview heat map scaffold. */
export const STUB_HEAT_RISKS = STUB_RISKS;

/** Overview KPI strip when Core overview is empty. */
export const STUB_KPIS = [
  {
    id: "actions",
    label: "Open resolution actions",
    value: "14",
    hint: "3 overdue",
    hintTone: "bad" as const,
    to: "resolutions",
  },
  {
    id: "risks",
    label: "High and critical risks",
    value: "3",
    hint: "1 worsening",
    hintTone: "warn" as const,
    to: "risks",
  },
  {
    id: "attendance",
    label: "Board attendance, 2026",
    value: "91%",
    hint: "+2 pts YoY",
    hintTone: "good" as const,
    to: "members",
  },
  {
    id: "declarations",
    label: "Declarations of interest due",
    value: "2",
    hint: "before Q3",
    hintTone: "warn" as const,
    to: "members",
  },
];

/** Overview-only display helpers for next-meeting stub. */
export const STUB_NEXT_MEETING_UI = {
  pack_due_label: "Issue to members by Thu 1 Oct",
  online_label: "Hybrid — Teams link issued with pack",
  confirmed: 6,
  quorum: 5,
  total_members: 9,
  awaiting: 2,
  apologies: 1,
  avatars: [
    { initials: "SD", kind: "yes" as const },
    { initials: "NS", kind: "yes" as const },
    { initials: "MM", kind: "yes" as const },
    { initials: "LN", kind: "yes" as const },
    { initials: "BH", kind: "yes" as const },
    { initials: "ZG", kind: "yes" as const },
    { initials: "TS", kind: "q" as const },
    { initials: "PK", kind: "q" as const },
    { initials: "SG", kind: "no" as const },
  ],
};
