/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/home/institution": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Institution portal KPIs, module states, and feed preview */
        get: operations["getInstitutionHome"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/home/service": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Service portal stats, recent activity, alerts */
        get: operations["getServiceHome"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/certification/applications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listCertificationApplications"];
        put?: never;
        post: operations["createCertificationApplication"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/certification/applications/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCertificationApplication"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/certification/applications/{id}/advance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["advanceCertificationApplication"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/certification/audits/overdue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listOverdueAudits"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/standards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listStandards"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/estore/checkout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["estoreCheckout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/verify/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Public certificate / mark verification */
        get: operations["verifyToken"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agent/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["agentAsk"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingest/applicability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["checkApplicability"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/adapters/momo/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** MTN MoMo payment callback */
        post: operations["momoCallback"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        InstitutionHome: {
            kpis: components["schemas"]["Kpi"][];
            modules: components["schemas"]["ModuleTile"][];
            feed: components["schemas"]["FeedItem"][];
        };
        ServiceHome: {
            stats: components["schemas"]["Kpi"][];
            services: components["schemas"]["ServiceCard"][];
            recent_activity: components["schemas"]["FeedItem"][];
            alerts: components["schemas"]["FeedItem"][];
        };
        Kpi: {
            key: string;
            label: string;
            value: unknown;
            trend?: string;
            /** @enum {string} */
            status?: "ok" | "warn" | "critical" | "unknown";
        };
        ModuleTile: {
            id: string;
            title: string;
            status: string;
            href?: string;
            watermark?: string;
        };
        ServiceCard: {
            id: string;
            title: string;
            description?: string;
            href?: string;
        };
        FeedItem: {
            id: string;
            type: string;
            title: string;
            body?: string;
            /** @enum {string} */
            severity?: "info" | "success" | "warn" | "critical";
            /** Format: date-time */
            created_at: string;
            href?: string;
        };
        CertificationApplication: {
            id: string;
            scheme: string;
            applicant: string;
            status: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        CreateCertificationApplication: {
            scheme: string;
            applicant_name: string;
            /** Format: email */
            contact_email?: string;
            confirm: boolean;
        };
        AuditSummary: {
            id: string;
            application_id: string;
            auditor?: string;
            scheme?: string;
            /** Format: date */
            due_date: string;
            status: string;
        };
        StandardSummary: {
            code: string;
            title: string;
            sector?: string;
            status?: string;
            buy_url?: string;
        };
        CheckoutResult: {
            order_id: string;
            status: string;
            payment_ref?: string;
            momo_reference?: string;
        };
        VerificationResult: {
            valid: boolean;
            token: string;
            subject?: string;
            /** Format: date-time */
            issued_at?: string;
            /** Format: date-time */
            expires_at?: string;
            details?: {
                [key: string]: unknown;
            };
        };
        AgentAskRequest: {
            message: string;
            context?: {
                [key: string]: unknown;
            };
            confirm_action_id?: string;
        };
        AgentAskResponse: {
            answer: string;
            citations?: components["schemas"]["Citation"][];
            tools_used?: string[];
            pending_action?: components["schemas"]["PendingAction"];
            buy_links?: components["schemas"]["BuyLink"][];
        };
        Citation: {
            source_id: string;
            title: string;
            /** @enum {string} */
            rights: "open" | "public" | "licensed";
            url?: string;
            excerpt?: string;
        };
        PendingAction: {
            id: string;
            tool: string;
            summary: string;
            mutates?: boolean;
        };
        BuyLink: {
            standard_code: string;
            title?: string;
            url: string;
        };
        ApplicabilityResult: {
            summary: string;
            steps: {
                order: number;
                title: string;
                detail?: string;
                href?: string;
            }[];
            citations: components["schemas"]["Citation"][];
            buy_links?: components["schemas"]["BuyLink"][];
        };
        Session: {
            access_token: string;
            /** @default bearer */
            token_type: string;
            user: components["schemas"]["SessionUser"];
        };
        SessionUser: {
            username: string;
            full_name: string;
            email?: string;
            roles: string[];
        };
    };
    responses: never;
    parameters: {
        IdPath: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getInstitutionHome: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstitutionHome"];
                };
            };
        };
    };
    getServiceHome: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceHome"];
                };
            };
        };
    };
    listCertificationApplications: {
        parameters: {
            query?: {
                status?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items?: components["schemas"]["CertificationApplication"][];
                    };
                };
            };
        };
    };
    createCertificationApplication: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCertificationApplication"];
            };
        };
        responses: {
            /** @description Created (pending confirmation if mutates confirm flow) */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CertificationApplication"];
                };
            };
        };
    };
    getCertificationApplication: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CertificationApplication"];
                };
            };
        };
    };
    advanceCertificationApplication: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    action?: string;
                    confirm: boolean;
                    comment?: string;
                };
            };
        };
        responses: {
            /** @description Advanced */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CertificationApplication"];
                };
            };
        };
    };
    listOverdueAudits: {
        parameters: {
            query?: {
                auditor?: string;
                scheme?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items?: components["schemas"]["AuditSummary"][];
                    };
                };
            };
        };
    };
    listStandards: {
        parameters: {
            query?: {
                q?: string;
                sector?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items?: components["schemas"]["StandardSummary"][];
                    };
                };
            };
        };
    };
    estoreCheckout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    items: {
                        standard_code: string;
                        qty: number;
                    }[];
                    /** @enum {string} */
                    payment_method?: "momo" | "invoice";
                    confirm: boolean;
                };
            };
        };
        responses: {
            /** @description Checkout initiated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckoutResult"];
                };
            };
        };
    };
    verifyToken: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerificationResult"];
                };
            };
        };
    };
    agentAsk: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentAskRequest"];
            };
        };
        responses: {
            /** @description Structured answer / pending action */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentAskResponse"];
                };
            };
        };
    };
    checkApplicability: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    query: string;
                    jurisdiction?: string;
                    sector?: string;
                    hs_code?: string;
                };
            };
        };
        responses: {
            /** @description Guided applicability result with citations */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicabilityResult"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    username: string;
                    /** Format: password */
                    password: string;
                };
            };
        };
        responses: {
            /** @description Session established */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionUser"];
                };
            };
        };
    };
    momoCallback: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Accepted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
