/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/home/institution": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Institution portal KPIs, module states, and feed preview */
        get: operations["getInstitutionHome"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/home/service": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Service portal stats, recent activity, alerts */
        get: operations["getServiceHome"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/certification/applications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listCertificationApplications"];
        put?: never;
        post: operations["createCertificationApplication"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/certification/applications/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCertificationApplication"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/certification/applications/{id}/act": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Workflow act (map §5) — guarded apply_workflow
         * @description Preferred transition API. Core passes values through; Frappe enforces expected_state, reason, idempotency (L4), and ToDo allocation (L1–L2). `/advance` remains as a compatibility alias.
         */
        post: operations["actCertificationApplication"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/standards/work-items/{id}/act": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Workflow act for Work Item (map §5) */
        post: operations["actWorkItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrology/jobs/{id}/act": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Workflow act for Calibration Job (map §5) */
        post: operations["actCalibrationJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tbt/notifications/{id}/act": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Workflow act for TBT Notification (map §5) */
        post: operations["actTbtNotification"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/governance/resolutions/{id}/act": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Workflow act for Board Resolution (map §5) */
        post: operations["actBoardResolution"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/governance/packs/{id}/act": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Workflow act for Board Pack (map §5) */
        post: operations["actBoardPack"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/field/visits/{id}/act": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Workflow act for Field Visit (map §5.7) */
        post: operations["actFieldVisit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/certification/applications/{id}/advance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Compatibility alias for /act
         * @deprecated
         */
        post: operations["advanceCertificationApplication"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/certification/audits/overdue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listOverdueAudits"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/standards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listStandards"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/estore/checkout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["estoreCheckout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/verify/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Public certificate / mark verification */
        get: operations["verifyToken"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agent/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["agentAsk"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingest/applicability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["checkApplicability"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/adapters/momo/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** MTN MoMo payment callback */
        post: operations["momoCallback"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/certification/audits/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Schedule, assign, complete, or submit Field outcome */
        patch: operations["patchCertificationAudit"];
        trace?: never;
    };
    "/certification/certificates/{id}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["revokeCertificate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/certification/certificates/{id}/renew": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["renewCertificate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/certification/certificates/{id}/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCertificatePdf"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/standards/ballots/{id}/vote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["voteBallot"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/approvals/{doctype}/{name}/escalate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Operator R-A2 escalate for SLA-breached queue item */
        post: operations["escalateApproval"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/field/me/audits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listFieldMyAudits"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/field/me/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getFieldMySummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/estore/cart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["upsertEstoreCart"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/estore/orders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getEstoreOrder"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/estore/licences/{id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["downloadEstoreLicence"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/hr/access-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAccessRequests"];
        put?: never;
        post: operations["createAccessRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/hr/expense-claims": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listExpenseClaims"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tbt/alerts/{id}/{action}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["triageTbtAlert"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingest/queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listIngestQueue"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingest/items/{id}/{action}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["curateIngestItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/governance/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Next meeting, pack track, KPIs, calendar, overdue actions */
        get: operations["getGovernanceOverview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/governance/meetings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listGovernanceMeetings"];
        put?: never;
        /** Schedule a board/committee meeting (creates pack draft) */
        post: operations["createGovernanceMeeting"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/governance/meetings/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Meeting detail with agenda, attendance, allowed_actions */
        get: operations["getGovernanceMeeting"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/governance/meetings/{id}/act": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["actOnGovernanceMeeting"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/governance/packs/{meeting}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Pack builder state for a meeting (sections + allowed_actions) */
        get: operations["getGovernancePack"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/governance/packs/{id}/sections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Include/exclude, reorder, or mark_ready sections */
        patch: operations["patchGovernancePackSections"];
        trace?: never;
    };
    "/governance/packs/{id}/assemble": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Assemble pack PDF from included Ready sections */
        post: operations["assembleGovernancePack"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/governance/packs/{id}/issue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Issue pack (409 if any included section is not Ready) */
        post: operations["issueGovernancePack"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/governance/board-pack": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Deprecated — outstanding board pack sections (prefer /governance/packs/{meeting})
         * @deprecated
         */
        get: operations["getBoardPackSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/governance/pack/{meeting}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Deprecated — assemble board pack (prefer POST /governance/packs/{id}/assemble)
         * @deprecated
         */
        post: operations["assembleBoardPack"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/governance/resolutions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listGovernanceResolutions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/governance/actions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listResolutionActions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/governance/risks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listGovernanceRisks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/governance/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listBoardMembers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/governance/bodies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listGovernanceBodies"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/governance/declarations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listGovernanceDeclarations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        InstitutionHome: {
            kpis: components["schemas"]["Kpi"][];
            modules: components["schemas"]["ModuleTile"][];
            feed: components["schemas"]["FeedItem"][];
        };
        ServiceHome: {
            stats: components["schemas"]["Kpi"][];
            services: components["schemas"]["ServiceCard"][];
            recent_activity: components["schemas"]["FeedItem"][];
            alerts: components["schemas"]["FeedItem"][];
        };
        Kpi: {
            key: string;
            label: string;
            value: unknown;
            trend?: string;
            /** @enum {string} */
            status?: "ok" | "warn" | "critical" | "unknown";
        };
        ModuleTile: {
            id: string;
            title: string;
            status: string;
            href?: string;
            watermark?: string;
        };
        ServiceCard: {
            id: string;
            title: string;
            description?: string;
            href?: string;
        };
        FeedItem: {
            id: string;
            type: string;
            title: string;
            body?: string;
            /** @enum {string} */
            severity?: "info" | "success" | "warn" | "critical";
            /** Format: date-time */
            created_at: string;
            href?: string;
        };
        CertificationApplication: {
            id: string;
            scheme: string;
            applicant: string;
            status: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        CreateCertificationApplication: {
            scheme: string;
            applicant_name: string;
            /** Format: email */
            contact_email?: string;
            confirm: boolean;
        };
        AuditSummary: {
            id: string;
            application_id: string;
            auditor?: string;
            scheme?: string;
            /** Format: date */
            due_date: string;
            status: string;
        };
        StandardSummary: {
            code: string;
            title: string;
            sector?: string;
            status?: string;
            buy_url?: string;
        };
        CheckoutResult: {
            order_id: string;
            status: string;
            payment_ref?: string;
            momo_reference?: string;
        };
        VerificationResult: {
            valid: boolean;
            token: string;
            subject?: string;
            /** Format: date-time */
            issued_at?: string;
            /** Format: date-time */
            expires_at?: string;
            details?: {
                [key: string]: unknown;
            };
        };
        AgentAskRequest: {
            message: string;
            context?: {
                [key: string]: unknown;
            };
            confirm_action_id?: string;
        };
        AgentAskResponse: {
            answer: string;
            citations?: components["schemas"]["Citation"][];
            tools_used?: string[];
            pending_action?: components["schemas"]["PendingAction"];
            buy_links?: components["schemas"]["BuyLink"][];
        };
        Citation: {
            source_id: string;
            title: string;
            /** @enum {string} */
            rights: "open" | "public" | "licensed";
            url?: string;
            excerpt?: string;
        };
        PendingAction: {
            id: string;
            tool: string;
            summary: string;
            mutates?: boolean;
        };
        BuyLink: {
            standard_code: string;
            title?: string;
            url: string;
        };
        ApplicabilityResult: {
            summary: string;
            steps: {
                order: number;
                title: string;
                detail?: string;
                href?: string;
            }[];
            citations: components["schemas"]["Citation"][];
            buy_links?: components["schemas"]["BuyLink"][];
        };
        Session: {
            access_token: string;
            /** @default bearer */
            token_type: string;
            user: components["schemas"]["SessionUser"];
        };
        SessionUser: {
            username: string;
            full_name: string;
            email?: string;
            roles: string[];
        };
        AllowedAction: {
            action: string;
            label: string;
            rule_id?: string | null;
            /** @default false */
            danger: boolean;
            consequence?: string | null;
        };
        ConfirmBody: {
            confirm: boolean;
        };
        /** @description Generic workflow transition (map §1.2 / §5.2) */
        WorkflowActBody: {
            /** @description Workflow action slug or Desk label */
            action: string;
            confirm: boolean;
            /** @description Must match current workflow_state (optimistic concurrency) */
            expected_state?: string | null;
            /** @description Replay returns the original result (L4); TTL 7 days */
            idempotency_key?: string | null;
            /** @description Required for reject/return/withdraw/suspend/cancel/override */
            reason?: string | null;
            comment?: string | null;
            payload?: {
                [key: string]: unknown;
            } | null;
        };
        AuditPatchBody: {
            action: string;
            confirm: boolean;
            payload?: {
                [key: string]: unknown;
            };
        };
        BallotVoteBody: {
            /** @enum {string} */
            vote: "approve" | "disapprove" | "abstain";
            comment?: string;
            confirm: boolean;
        };
        EscalateBody: {
            confirm: boolean;
            reason?: string;
        };
        CartItemBody: {
            code: string;
            /** @default 1 */
            qty: number;
        };
        CartBody: {
            items?: components["schemas"]["CartItemBody"][];
            confirm?: boolean;
        };
        AccessRequestBody: {
            reason: string;
            requested_roles?: string[];
            confirm: boolean;
        };
        /** @enum {string} */
        PackSectionStatus: "awaiting" | "ready" | "overdue";
        /** @enum {string} */
        PackSectionSource: "live_module" | "upload" | "secretariat";
        PackSection: {
            id: string;
            title: string;
            status: components["schemas"]["PackSectionStatus"];
            included: boolean;
            source?: components["schemas"]["PackSectionSource"];
            module_key?: string | null;
            owner?: string | null;
            idx?: number | null;
            file_url?: string | null;
            /** @default false */
            restricted: boolean;
        };
        /** @description Segmented pack readiness track for Overview / meeting drawer */
        PackTrack: {
            pack_id?: string | null;
            meeting_id?: string | null;
            due_label?: string | null;
            /** @default 0 */
            outstanding_sections: number;
            sections: components["schemas"]["PackSection"][];
        };
        GovernanceKpis: {
            /** @default 0 */
            open_actions: number;
            /** @default 0 */
            overdue_actions: number;
            /** @default 0 */
            high_critical_risks: number;
            /** @default 0 */
            worsening_risks: number;
            board_attendance_pct?: number | null;
            /** @default 0 */
            declarations_due: number;
        };
        GovernanceCalendarItem: {
            id: string;
            title: string;
            /** Format: date */
            date: string;
            kind?: string | null;
            href?: string | null;
        };
        GovernanceOverview: {
            next_meeting?: components["schemas"]["GovernanceMeeting"];
            pack_track: components["schemas"]["PackTrack"];
            kpis: components["schemas"]["GovernanceKpis"];
            calendar: components["schemas"]["GovernanceCalendarItem"][];
            overdue_actions: components["schemas"]["ResolutionAction"][];
            recent_resolutions: components["schemas"]["GovernanceResolution"][];
            /** @description Optional 5×5 residual L×I counts for Overview heat map */
            heat_cells?: {
                L: number;
                I: number;
                count: number;
            }[];
        };
        MeetingAgendaItem: {
            id: string;
            item: string;
            presenter?: string | null;
            purpose?: string | null;
            paper?: string | null;
        };
        MeetingAttendance: {
            member: string;
            member_name?: string | null;
            rsvp?: string | null;
            attended?: boolean | null;
            apology?: boolean | null;
        };
        GovernanceMeeting: {
            id: string;
            title: string;
            body?: string | null;
            body_name?: string | null;
            /** @enum {string|null} */
            meeting_type?: "Ordinary" | "Special" | "AGM" | null;
            /** Format: date */
            date?: string | null;
            start_time?: string | null;
            /** Format: date-time */
            scheduled_at?: string | null;
            venue?: string | null;
            /** @default false */
            hybrid: boolean;
            online_link?: string | null;
            /** Format: date */
            pack_deadline?: string | null;
            status: string;
            agenda?: components["schemas"]["MeetingAgendaItem"][];
            attendance?: components["schemas"]["MeetingAttendance"][];
            pack_id?: string | null;
            pack_track?: components["schemas"]["PackTrack"];
            allowed_actions?: components["schemas"]["AllowedAction"][];
        };
        GovernanceMeetingCreate: {
            title: string;
            body?: string | null;
            /**
             * @default Ordinary
             * @enum {string}
             */
            meeting_type: "Ordinary" | "Special" | "AGM";
            /** Format: date */
            date?: string;
            start_time?: string;
            /** Format: date-time */
            scheduled_at?: string;
            venue?: string;
            /** @default false */
            hybrid: boolean;
            online_link?: string;
            /** Format: date */
            pack_deadline?: string;
            confirm: boolean;
        };
        GovernanceMeetingAct: {
            /** @enum {string} */
            action: "reschedule" | "cancel" | "record_attendance" | "start_minutes" | "submit_minutes" | "approve_minutes";
            confirm: boolean;
            /** @description Action-specific fields (new dates, attendance rows, etc.) */
            payload?: {
                [key: string]: unknown;
            };
        };
        GovernancePack: {
            id: string;
            meeting: string;
            meeting_title?: string | null;
            /** @default 1 */
            version: number;
            /** @enum {string} */
            status: "Draft" | "Assembled" | "Issued";
            sections: components["schemas"]["PackSection"][];
            assembled_file?: string | null;
            pages?: number | null;
            /** Format: date-time */
            issued_on?: string | null;
            due_label?: string | null;
            /** @default 0 */
            outstanding_sections: number;
            allowed_actions?: components["schemas"]["AllowedAction"][];
        };
        GovernancePackSectionPatch: {
            id: string;
            included?: boolean;
            idx?: number;
            status?: components["schemas"]["PackSectionStatus"];
            mark_ready?: boolean;
        };
        GovernancePackSectionsPatch: {
            confirm: boolean;
            sections: components["schemas"]["GovernancePackSectionPatch"][];
        };
        GovernancePackAssembleResult: {
            id: string;
            version: number;
            pages?: number | null;
            file_url?: string | null;
            status?: string | null;
        };
        /** @description Deprecated thin summary — prefer GovernancePack / PackTrack */
        BoardPackSummary: {
            due_label: string;
            outstanding_sections: number;
            sections: {
                title: string;
                status: string;
            }[];
        };
        GovernanceResolution: {
            id: string;
            title: string;
            meeting?: string | null;
            text?: string | null;
            /** @enum {string|null} */
            outcome?: "Passed" | "Rejected" | "Deferred" | null;
            votes_for?: number | null;
            votes_against?: number | null;
            votes_abstained?: number | null;
            status: string;
            /** Format: date */
            date?: string | null;
            allowed_actions?: components["schemas"]["AllowedAction"][];
        };
        ResolutionAction: {
            id: string;
            resolution?: string | null;
            description: string;
            owner?: string | null;
            /** Format: date */
            due_date?: string | null;
            /** @default 0 */
            progress: number;
            /** @enum {string} */
            status: "Open" | "Overdue" | "Completed";
            /** @default false */
            report_in_pack: boolean;
        };
        /** @enum {string} */
        RiskBand: "critical" | "high" | "medium" | "low";
        /** @enum {string} */
        RiskTrend: "improving" | "stable" | "worsening";
        GovernanceRisk: {
            id: string;
            title: string;
            cause_consequence?: string | null;
            category?: string | null;
            owner?: string | null;
            inherent_likelihood?: number | null;
            inherent_impact?: number | null;
            controls?: string | null;
            residual_likelihood: number;
            residual_impact: number;
            /** @description Server-computed residual L × I */
            score: number;
            band: components["schemas"]["RiskBand"];
            trend?: components["schemas"]["RiskTrend"];
            appetite_threshold?: number | null;
            status: string;
            /** @default false */
            flagged_for_pack: boolean;
        };
        BoardMember: {
            id: string;
            full_name: string;
            title?: string | null;
            /** @enum {string|null} */
            role?: "Chair" | "Vice" | "Member" | "Ex officio" | null;
            committees?: string[];
            /** Format: date */
            term_start?: string | null;
            /** Format: date */
            term_end?: string | null;
            attendance_pct?: number | null;
            /** @default false */
            declaration_due: boolean;
        };
        GovernanceBody: {
            id: string;
            name: string;
            /** @enum {string} */
            type: "Board" | "Committee";
            chair?: string | null;
            quorum?: number | null;
            meeting_frequency?: string | null;
            members?: string[];
        };
        GovernanceDeclaration: {
            id: string;
            member: string;
            member_name?: string | null;
            /** @enum {string} */
            kind: "Annual" | "Meeting";
            meeting?: string | null;
            agenda_item?: string | null;
            interest: string;
            /** @enum {string|null} */
            action?: "Recuse" | "Note" | null;
            /** Format: date */
            filed_on: string;
        };
        GovernanceMeetingSummary: components["schemas"]["GovernanceMeeting"];
        GovernanceResolutionSummary: components["schemas"]["GovernanceResolution"];
        GovernanceRiskSummary: components["schemas"]["GovernanceRisk"];
    };
    responses: never;
    parameters: {
        IdPath: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getInstitutionHome: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstitutionHome"];
                };
            };
        };
    };
    getServiceHome: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceHome"];
                };
            };
        };
    };
    listCertificationApplications: {
        parameters: {
            query?: {
                status?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items?: components["schemas"]["CertificationApplication"][];
                    };
                };
            };
        };
    };
    createCertificationApplication: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCertificationApplication"];
            };
        };
        responses: {
            /** @description Created (pending confirmation if mutates confirm flow) */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CertificationApplication"];
                };
            };
        };
    };
    getCertificationApplication: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CertificationApplication"];
                };
            };
        };
    };
    actCertificationApplication: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkflowActBody"];
            };
        };
        responses: {
            /** @description Transition applied */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CertificationApplication"];
                };
            };
        };
    };
    actWorkItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkflowActBody"];
            };
        };
        responses: {
            /** @description Transition applied */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    actCalibrationJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkflowActBody"];
            };
        };
        responses: {
            /** @description Transition applied */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    actTbtNotification: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkflowActBody"];
            };
        };
        responses: {
            /** @description Transition applied */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    actBoardResolution: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkflowActBody"];
            };
        };
        responses: {
            /** @description Transition applied */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    actBoardPack: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkflowActBody"];
            };
        };
        responses: {
            /** @description Transition applied */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    actFieldVisit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkflowActBody"];
            };
        };
        responses: {
            /** @description Transition applied */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    advanceCertificationApplication: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkflowActBody"];
            };
        };
        responses: {
            /** @description Advanced */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CertificationApplication"];
                };
            };
        };
    };
    listOverdueAudits: {
        parameters: {
            query?: {
                auditor?: string;
                scheme?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items?: components["schemas"]["AuditSummary"][];
                    };
                };
            };
        };
    };
    listStandards: {
        parameters: {
            query?: {
                q?: string;
                sector?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items?: components["schemas"]["StandardSummary"][];
                    };
                };
            };
        };
    };
    estoreCheckout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    items: {
                        standard_code: string;
                        qty: number;
                    }[];
                    /** @enum {string} */
                    payment_method?: "momo" | "invoice";
                    confirm: boolean;
                };
            };
        };
        responses: {
            /** @description Checkout initiated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckoutResult"];
                };
            };
        };
    };
    verifyToken: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerificationResult"];
                };
            };
        };
    };
    agentAsk: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentAskRequest"];
            };
        };
        responses: {
            /** @description Structured answer / pending action */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentAskResponse"];
                };
            };
        };
    };
    checkApplicability: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    query: string;
                    jurisdiction?: string;
                    sector?: string;
                    hs_code?: string;
                };
            };
        };
        responses: {
            /** @description Guided applicability result with citations */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicabilityResult"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    username: string;
                    /** Format: password */
                    password: string;
                };
            };
        };
        responses: {
            /** @description Session established */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionUser"];
                };
            };
        };
    };
    momoCallback: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Accepted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    patchCertificationAudit: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string;
            };
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuditPatchBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    revokeCertificate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmBody"];
            };
        };
        responses: {
            /** @description Revoked */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    renewCertificate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmBody"];
            };
        };
        responses: {
            /** @description Renewed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getCertificatePdf: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Signed download URL */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        download_url?: string | null;
                    };
                };
            };
        };
    };
    voteBallot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BallotVoteBody"];
            };
        };
        responses: {
            /** @description Vote recorded */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    escalateApproval: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doctype: string;
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EscalateBody"];
            };
        };
        responses: {
            /** @description Escalation result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listFieldMyAudits: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Audits assigned to current auditor */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getFieldMySummary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Next audit, schedule chips, unread */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    upsertEstoreCart: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CartBody"];
            };
        };
        responses: {
            /** @description Cart snapshot */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getEstoreOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Order status (poll for MoMo) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    downloadEstoreLicence: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Signed licence download URL */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listAccessRequests: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Access request queue */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createAccessRequest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccessRequestBody"];
            };
        };
        responses: {
            /** @description Created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listExpenseClaims: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Expense claims for current user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    triageTbtAlert: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
                action: "assess" | "publish" | "dismiss";
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmBody"];
            };
        };
        responses: {
            /** @description Triage result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listIngestQueue: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Curation queue */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    curateIngestItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
                action: "approve" | "reject" | "flag_rights";
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmBody"];
            };
        };
        responses: {
            /** @description Curation result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getGovernanceOverview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GovernanceOverview"];
                };
            };
        };
    };
    listGovernanceMeetings: {
        parameters: {
            query?: {
                /** @description Governance Body name/id filter */
                body?: string;
                status?: string;
                q?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["GovernanceMeeting"][];
                    };
                };
            };
        };
    };
    createGovernanceMeeting: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GovernanceMeetingCreate"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GovernanceMeeting"];
                };
            };
        };
    };
    getGovernanceMeeting: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GovernanceMeeting"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    actOnGovernanceMeeting: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GovernanceMeetingAct"];
            };
        };
        responses: {
            /** @description Updated meeting */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GovernanceMeeting"];
                };
            };
        };
    };
    getGovernancePack: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meeting: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GovernancePack"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    patchGovernancePackSections: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GovernancePackSectionsPatch"];
            };
        };
        responses: {
            /** @description Updated pack */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GovernancePack"];
                };
            };
        };
    };
    assembleGovernancePack: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmBody"];
            };
        };
        responses: {
            /** @description Assembled */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GovernancePackAssembleResult"];
                };
            };
        };
    };
    issueGovernancePack: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmBody"];
            };
        };
        responses: {
            /** @description Issued */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GovernancePack"];
                };
            };
            /** @description Included section not Ready */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getBoardPackSummary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoardPackSummary"];
                };
            };
        };
    };
    assembleBoardPack: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meeting: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmBody"];
            };
        };
        responses: {
            /** @description Assembled */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoardPackSummary"];
                };
            };
        };
    };
    listGovernanceResolutions: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["GovernanceResolution"][];
                    };
                };
            };
        };
    };
    listResolutionActions: {
        parameters: {
            query?: {
                status?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["ResolutionAction"][];
                    };
                };
            };
        };
    };
    listGovernanceRisks: {
        parameters: {
            query?: {
                /** @description Residual likelihood (1–5) */
                L?: number;
                /** @description Residual impact (1–5) */
                I?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["GovernanceRisk"][];
                    };
                };
            };
        };
    };
    listBoardMembers: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["BoardMember"][];
                    };
                };
            };
        };
    };
    listGovernanceBodies: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["GovernanceBody"][];
                    };
                };
            };
        };
    };
    listGovernanceDeclarations: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["GovernanceDeclaration"][];
                    };
                };
            };
        };
    };
}
