/**
 * Field demo seed — visits across every type and state, plus samples in custody. Fictional.
 * Parents line up with the certification, metrology and CRM seeds (same ids).
 */
import { isoIn } from "../store/localStore";
import { CHECKLISTS } from "./defs";
import type { ChecklistItem, FieldVisit, Sample, VisitType } from "./types";

const h = (at: string, actor: string, action: string, from?: string, to?: string, extra: Record<string, string> = {}) => ({ at, actor, action, from, to, ...extra });

function checklist(type: VisitType, answered = 0): { checklist_version: string; checklist: ChecklistItem[] } {
  const key = { cert_audit: "ms_audit", factory_inspection: "factory", market_sampling: "sampling", complaint_investigation: "investigation", onsite_calibration: "onsite_cal", batch_inspection: "batch", import_inspection: "batch", legal_metrology: "onsite_cal" }[type];
  const c = CHECKLISTS[key];
  return {
    checklist_version: c.version,
    checklist: c.items.map((i, n) => ({ ...i, answer: n < answered ? (n === 3 ? "no" : "yes") : undefined })),
  };
}

function base(p: Partial<FieldVisit> & Pick<FieldVisit, "id" | "type" | "state" | "title" | "client" | "planned_date">): FieldVisit {
  return {
    seq: 1,
    history: [],
    client_email: "",
    site: { name: p.client, address: "Eswatini", contact: "Site contact" },
    duration_days: 1,
    team: [],
    created_at: isoIn(-14),
    created_by: "Thandeka Simelane",
    findings: [],
    notes: "",
    photos: [],
    signatures: [],
    cal_points: [],
    sample_ids: [],
    ...checklist(p.type),
    ...p,
  } as FieldVisit;
}

export function seedVisits(): FieldVisit[] {
  return [
    base({
      id: "FV-26-0140",
      type: "cert_audit",
      state: "Submitted",
      title: "Stage 2 audit — Mhlume Packaging (ISO 9001)",
      parent: { doctype: "Certification Application", name: "CERT-APP-26-0058", label: "CERT-APP-26-0058", link: "/certification/applications/CERT-APP-26-0058" },
      client: "Mhlume Packaging (Pty) Ltd",
      client_email: "quality@mhlumepack.example.sz",
      site: { name: "Mhlume factory", address: "Plot 12, Mhlume Industrial Area", contact: "B. Magagula", phone: "+268 2313 4000", gps: { lat: -26.035, lng: 31.85 } },
      planned_date: isoIn(-5),
      duration_days: 2,
      auditor_days: 3,
      lead: "Lindiwe Dube",
      team: ["Sabelo Mamba"],
      scope: "Manufacture of corrugated packaging",
      pack: { downloaded_at: isoIn(-6), summary: "Stage 1 raised 1 observation on document control.", previous_ncs: ["OBS: Document control — obsolete forms in use"], open_samples: [] },
      ...checklist("cert_audit", 8),
      checkin: { at: isoIn(-5, 8), lat: -26.0351, lng: 31.8502, accuracy: 12, by: "Lindiwe Dube" },
      findings: [
        { id: "F-1", clause: "ISO 9001 §7.1.5", severity: "minor", statement: "Two line scales had no calibration records for the last 12 months.", photos: ["scale-tag.jpg"] },
        { id: "F-2", clause: "ISO 9001 §9.2", severity: "minor", statement: "Internal audit programme did not cover dispatch in the cycle.", photos: [] },
      ],
      notes: "Closing meeting held with the MD and QA manager. Recommendation: certify once the two minors are closed.",
      photos: [{ id: "P-1", at: isoIn(-5, 10), name: "scale-tag.jpg", caption: "Scale without calibration label", hash: "a3f9c1" }],
      signatures: [
        { role: "lead", name: "Lindiwe Dube", at: isoIn(-4, 15) },
        { role: "client", name: "B. Magagula", title: "QA Manager", at: isoIn(-4, 15) },
      ],
      duties: { Lead: ["Lindiwe Dube"] },
      history: [
        h(isoIn(-14), "Thandeka Simelane", "Assign team", "Planned", "Assigned"),
        h(isoIn(-13), "Lindiwe Dube", "Accept visit", "Assigned", "Accepted"),
        h(isoIn(-12), "B. Magagula (customer)", "Confirmed the date", "Accepted", "Confirmed"),
        h(isoIn(-5, 8), "Lindiwe Dube", "Check in", "Confirmed", "In Progress"),
        h(isoIn(-4, 16), "Lindiwe Dube", "Submit report", "In Progress", "Submitted"),
      ],
      seq: 5,
    }),
    base({
      id: "FV-26-0151",
      type: "cert_audit",
      state: "Accepted",
      title: "Stage 1 audit — Ubombo Honey (ISO 9001)",
      parent: { doctype: "Certification Application", name: "CERT-APP-26-0053", label: "CERT-APP-26-0053", link: "/certification/applications/CERT-APP-26-0053" },
      client: "Ubombo Honey Co. (Pty) Ltd",
      client_email: "demo",
      site: { name: "Ubombo processing plant", address: "Big Bend Road, Siteki", contact: "Sipho Nkambule", phone: "+268 7602 1188", gps: { lat: -26.56, lng: 31.79 } },
      planned_date: isoIn(6, 8),
      duration_days: 1,
      auditor_days: 1,
      lead: "Lindiwe Dube",
      team: [],
      scope: "Processing and bottling of honey",
      duties: { Lead: ["Lindiwe Dube"] },
      history: [h(isoIn(-3), "Thandeka Simelane", "Assign team", "Planned", "Assigned"), h(isoIn(-2), "Lindiwe Dube", "Accept visit", "Assigned", "Accepted")],
      seq: 2,
    }),
    base({
      id: "FV-26-0147",
      type: "factory_inspection",
      state: "Closed",
      title: "Factory inspection — Mankayane Roof Tiles (SZNS mark)",
      parent: { doctype: "Certification Application", name: "CERT-APP-26-0047", label: "CERT-APP-26-0047", link: "/certification/applications/CERT-APP-26-0047" },
      client: "Mankayane Roof Tiles",
      client_email: "info@mankayanetiles.example.sz",
      site: { name: "Mankayane yard", address: "Mankayane town", contact: "J. Shabalala" },
      planned_date: isoIn(-10),
      lead: "Mfanasibili Vilakati",
      ...checklist("factory_inspection", 5),
      sample_ids: ["SMP-26-0412"],
      review: { by: "Thandeka Simelane", at: isoIn(-8), outcome: "closed" },
      duties: { Lead: ["Mfanasibili Vilakati"], Reviewer: ["Thandeka Simelane"] },
      history: [h(isoIn(-10, 8), "Mfanasibili Vilakati", "Check in", "Confirmed", "In Progress"), h(isoIn(-10, 15), "Mfanasibili Vilakati", "Submit report", "In Progress", "Submitted"), h(isoIn(-8), "Thandeka Simelane", "Accept report & close", "Submitted", "Closed")],
      seq: 6,
    }),
    base({
      id: "FV-26-0155",
      type: "market_sampling",
      state: "Confirmed",
      title: "Market sampling — Manzini market (CS-26-0141)",
      parent: { doctype: "Case", name: "CS-26-0141", label: "CS-26-0141 · SZNS mark on uncertified roof tiles", link: "/crm/cases/CS-26-0141" },
      client: "Traders, Manzini market",
      client_email: "",
      site: { name: "Manzini market — hardware row", address: "Manzini market, Mhlakuvane St", contact: "Market supervisor", phone: "+268 2505 2111", directions: "Hardware stalls are behind the bus rank, row C.", gps: { lat: -26.4891, lng: 31.3773 } },
      planned_date: isoIn(0, 9),
      lead: "Mfanasibili Vilakati",
      created_by: "Phindile Shongwe",
      scope: "Roof tiles bearing the SZNS mark — brand 'Mankayane'",
      duties: { Lead: ["Mfanasibili Vilakati"] },
      history: [h(isoIn(-2), "Mandla Nxumalo", "Assign team", "Planned", "Assigned"), h(isoIn(-1), "Mfanasibili Vilakati", "Accept visit", "Assigned", "Confirmed", { note: "Unannounced visit — no customer confirmation." })],
      seq: 2,
    }),
    base({
      id: "FV-26-0158",
      type: "onsite_calibration",
      state: "Assigned",
      title: "On-site calibration — Royal Valley Sugar weighbridge",
      parent: { doctype: "Calibration Job", name: "CJ-26-0240", label: "CJ-26-0240", link: "/metrology/jobs/CJ-26-0240" },
      client: "Royal Valley Sugar Estates",
      client_email: "eng@royalvalley.example.sz",
      site: { name: "Mhlume mill weighbridge", address: "Mhlume Sugar Mill", contact: "Nomsa Dlamini", phone: "+268 2313 1000" },
      planned_date: isoIn(2, 8),
      lead: "Musa Khumalo",
      created_by: "Ayanda Ndlovu",
      scope: "Weighbridge 60 t, 5 test loads",
      history: [h(isoIn(-1), "Ayanda Ndlovu", "Assign team", "Planned", "Assigned")],
      seq: 1,
    }),
    base({
      id: "FV-26-0160",
      type: "cert_audit",
      state: "Planned",
      title: "Surveillance audit 1 — Ubombo Honey (HACCP)",
      parent: { doctype: "Certification", name: "CRT-25-0311", label: "CRT-25-0311", link: "/certification/certificates/CRT-25-0311" },
      client: "Ubombo Honey Co. (Pty) Ltd",
      client_email: "demo",
      site: { name: "Ubombo processing plant", address: "Big Bend Road, Siteki", contact: "Sipho Nkambule" },
      planned_date: isoIn(21, 8),
      auditor_days: 1,
      created_by: "System",
      history: [h(isoIn(-1), "System", "Planned from surveillance due (R-C5)", undefined, "Planned")],
      seq: 1,
    }),
    base({
      id: "FV-26-0149",
      type: "complaint_investigation",
      state: "Aborted",
      title: "Investigation — Nhlangano Grain Millers short weight (CS-26-0120)",
      parent: { doctype: "Case", name: "CS-26-0120", label: "CS-26-0120 · Maize meal bags under-weight", link: "/crm/cases/CS-26-0120" },
      client: "Nhlangano Grain Millers",
      client_email: "quality@nhlangano.example.sz",
      site: { name: "Nhlangano mill", address: "Nhlangano industrial site", contact: "Mill manager" },
      planned_date: isoIn(-1, 9),
      lead: "Mfanasibili Vilakati",
      abort: { code: "premises_closed", reason: "Mill closed for maintenance — gate locked, no staff on site.", at: isoIn(-1, 10), evidence: "gate-photo.jpg" },
      duties: { Lead: ["Mfanasibili Vilakati"] },
      history: [h(isoIn(-1, 10), "Mfanasibili Vilakati", "Abort visit", "Confirmed", "Aborted", { reason: "Mill closed for maintenance — gate locked, no staff on site." })],
      seq: 4,
    }),
    base({
      id: "FV-26-0136",
      type: "cert_audit",
      state: "Closed",
      title: "Stage 2 audit — Valley Dairy (ISO 22000)",
      parent: { doctype: "Certification Application", name: "CERT-APP-26-0051", label: "CERT-APP-26-0051", link: "/certification/applications/CERT-APP-26-0051" },
      client: "Valley Dairy Cooperative",
      client_email: "demo",
      planned_date: isoIn(-12),
      lead: "Sabelo Mamba",
      team: ["Nonhlanhla Dlamini"],
      ...checklist("cert_audit", 8),
      review: { by: "Thandeka Simelane", at: isoIn(-9), outcome: "closed" },
      duties: { Lead: ["Sabelo Mamba"], Reviewer: ["Thandeka Simelane"] },
      history: [h(isoIn(-9), "Thandeka Simelane", "Accept report & close", "Submitted", "Closed")],
      seq: 6,
    }),
  ];
}

export function seedSamples(): Sample[] {
  return [
    {
      id: "SMP-26-0412",
      seal: "ES-SEAL-104412",
      visit_id: "FV-26-0147",
      parent: { doctype: "Certification Application", name: "CERT-APP-26-0047", label: "CERT-APP-26-0047" },
      product: "Concrete roof tile",
      brand: "Mankayane",
      batch: "MT-2609",
      quantity: "6 tiles",
      split: { test: 4, retained: 1, client: 1 },
      collected_by: "Mfanasibili Vilakati",
      collected_at: isoIn(-10, 11),
      witness: "J. Shabalala",
      state: "Testing",
      holder: "LIMS — Materials lab",
      condition: "ok",
      test_request_id: "LT-26-0088",
      tests: "SZNS 210 transverse strength, water absorption",
      custody: [
        { at: isoIn(-10, 11), actor: "Mfanasibili Vilakati", action: "Collected and sealed" },
        { at: isoIn(-9, 9), actor: "Mfanasibili Vilakati", action: "Handed over to lab reception" },
        { at: isoIn(-9, 9), actor: "Precious Tfwala", action: "Received — seal intact" },
        { at: isoIn(-9, 10), actor: "Precious Tfwala", action: "Sent for testing (LT-26-0088)" },
      ],
    },
    {
      id: "SMP-26-0398",
      seal: "ES-SEAL-103980",
      visit_id: "FV-26-0131",
      parent: { doctype: "Certification Application", name: "CERT-APP-26-0049", label: "CERT-APP-26-0049" },
      product: "Portland cement 42.5N, 50 kg",
      brand: "Sidvokodvo",
      batch: "SC-2608-14",
      quantity: "3 bags",
      split: { test: 2, retained: 1, client: 0 },
      collected_by: "Bongani Hlophe",
      collected_at: isoIn(-24, 11),
      state: "Result",
      holder: "Retained store",
      condition: "ok",
      test_request_id: "LT-26-0081",
      tests: "SZNS 044 compressive strength, setting time",
      result: "pass",
      result_note: "All parameters within limits.",
      custody: [
        { at: isoIn(-24, 11), actor: "Bongani Hlophe", action: "Collected and sealed" },
        { at: isoIn(-23, 9), actor: "Precious Tfwala", action: "Received — seal intact" },
        { at: isoIn(-15), actor: "Ayanda Ndlovu", action: "Result approved: pass" },
      ],
    },
    {
      id: "SMP-26-0425",
      seal: "ES-SEAL-104425",
      visit_id: "FV-26-0150",
      parent: { doctype: "Case", name: "CS-26-0136", label: "CS-26-0136 · Bottled water with sediment" },
      product: "Still water 5 L",
      brand: "Ezulwini",
      batch: "EZ-0923-B",
      quantity: "4 bottles",
      split: { test: 2, retained: 1, client: 1 },
      collected_by: "Mfanasibili Vilakati",
      collected_at: isoIn(-1, 14),
      witness: "Shop owner (Ezulwini Spar)",
      state: "In Transit",
      holder: "Mfanasibili Vilakati",
      custody: [
        { at: isoIn(-1, 14), actor: "Mfanasibili Vilakati", action: "Collected and sealed", gps: { lat: -26.42, lng: 31.17 } },
        { at: isoIn(-1, 16), actor: "Mfanasibili Vilakati", action: "Handed over for transport to lab" },
      ],
    },
  ];
}
